// Code generated by goctl. DO NOT EDIT.
package types

type UserLoginRequest struct {
	AccountNumber string `json:"account_number"`
	Password      string `json:"password"`
}

type UserLoginResponse struct {
	UserId        int64  `json:"user_id"`
	AccountNumber string `json:"account_number"`
	Token         string `json:"token"`
}

type UserInfoRequest struct {
}

type UserInfoResponse struct {
	User *User `json:"user"`
}

type UserRegisterRequest struct {
	Name     string `json:"name"`
	BankName string `json:"bank_name"`
	Phone    string `json:"phone"`
	Password string `json:"password"`
}

type UserRegisterResponse struct {
	UserId        int64  `json:"user_id"`
	AccountNumber string `json:"account_number"`
}

type PingRequest struct {
}

type PingResponse struct {
	Message string `json:"message"`
}

type User struct {
	Id            int64  `json:"id"`
	AccountNumber string `json:"account_number"`
	Name          string `json:"name"`
	BankName      string `json:"bank_name"`
	Phone         string `json:"phone"`
	Balance       int64  `json:"balance"`
}
