// Code generated by goctl. DO NOT EDIT.
package types

type GetBalanceRequest struct {
}

type GetBalanceResponse struct {
	TotalBalance float64 `json:"total_balance"`
	DailyLimit   float64 `json:"daily_limit"`
	Date         string  `json:"date"`
}

type ChangePasswordRequest struct {
	NewPassword string `json:"new_password" vd:"len($)>=6;msg:'密码长度最少6位'"`
}

type ChangePasswordResponse struct {
}

type TransferMoneyRequest struct {
	ToAccountNumber string  `json:"to_account_number"`
	Amount          float64 `json:"amount" vd:"$>0&&$<1000000;msg:'转账金额不合法'"`
}

type TransferMoneyResponse struct {
}

type GetTransactionMoneyRequest struct {
	PageNum  int64 `form:"page_num" vd:"$>0;msg:'页码不合法'"`
	PageSize int64 `form:"page_size" vd:"$>0&&$<100;msg:'页大小不合法'"`
}

type GetTransactionMoneyResponse struct {
	Total        int64          `json:"total"`
	Transactions []*Transaction `json:"transactions"`
}

type PutMoneyRequest struct {
	Amount float64 `json:"amount" vd:"$>0&&$<1000000;msg:'转账金额不合法'"`
}

type PutMoneyResponse struct {
	Balance float64 `json:"balance"`
}

type TakeMoneyRequest struct {
	Amount float64 `json:"amount" vd:"$>0&&$<1000000;msg:'取款金额不合法'"`
}

type TakeMoneyResponse struct {
	Balance float64 `json:"balance"`
}

type UserLoginRequest struct {
	AccountNumber string `json:"account_number"`
	Password      string `json:"password"`
}

type UserLoginResponse struct {
	UserId        int64  `json:"user_id"`
	AccountNumber string `json:"account_number"`
	Token         string `json:"token"`
}

type UserInfoRequest struct {
}

type UserInfoResponse struct {
	User *User `json:"user"`
}

type UserRegisterRequest struct {
	Name     string `json:"name"`
	IdCard   string `json:"id_card"`
	BankName string `json:"bank_name"`
	Phone    string `json:"phone"`
	Password string `json:"password"`
}

type UserRegisterResponse struct {
	UserId        int64  `json:"user_id"`
	AccountNumber string `json:"account_number"`
}

type PingRequest struct {
}

type PingResponse struct {
	Message string `json:"message"`
}

type Transaction struct {
	Id          int64   `json:"id"`
	UserId      int64   `json:"user_id"`
	Amount      float64 `json:"amount"`
	Type        string  `json:"type"`
	Description string  `json:"description"`
	CreateTime  string  `json:"create_time"`
}

type User struct {
	Id            int64   `json:"id"`
	AccountNumber string  `json:"account_number"`
	Name          string  `json:"name"`
	BankName      string  `json:"bank_name"`
	Phone         string  `json:"phone"`
	Balance       float64 `json:"balance"`
}
